image:
- Ubuntu
- Visual Studio 2015

platform:
  - x86
  - x64
  
configuration:
- Debug
- Release

before_build:
  - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=%CONFIGURATION%

build_script:
  - cmake --build _builds --config %CONFIGURATION%

test_script:
  - ps: cd _builds
  - ctest -VV -C %CONFIGURATION%